- hosts: mysql_server
  become: true
  tasks:
    - name: Add MySQL repository
      apt_repository:
        repo: ppa:mysql.com/mysql/8.0 
        state: present
        update_cache: yes

    - name: Update package lists
      apt:
        update_cache: yes

    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present

    - name: Secure MySQL installation
      mysql_secure_installation:
        password: "{{ mysql_root_password }}"

    - name: Start and enable MySQL service
      systemd:
        name: mysql
        state: started
        enabled: yes

    - name: Verify MySQL connection
      mysql_host: localhost
        mysql_user: root
        mysql_password: "{{ mysql_root_password }}"
        check_login: yes